### ISSUE TITLE
New Activity Account Bugs

### ISSUE THREAD

**Issue by TBurg64personal** [TBurg64personal/PuppyGram#1]
When I committed this, it said there was an error but i ran it myself and the phone worked, so if you can figure the error that would be great. 
Also, when running, it looked like the "Create New Account" was actually "Welcome To" which needs to be fixed
The submit button also when it was ran was on top of user input, that needs to be moved => maybe look into scroll bar features.

**Comment by NoahKrill11** [comment]
Has this been resolved?
